#cloud-config
users:
  - name: dylan
    shell: /bin/bash
    groups:
      - lxd
      - microk8s
      - docker
      - sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - |
      %public_key%
ssh_deletekeys: false
package_update: true
package_upgrade: true
package_reboot_if_required: true
write_files:
  - path: /home/dylan/.ssh/known_hosts
    owner: 'dylan:dylan'
    permissions: '0600'
    defer: true # Run after user creation
    content: |
      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
  - path: /home/dylan/setup
    owner: 'dylan:dylan'
    permissions: '0755'
    defer: true # Run after user creation
    content: |
      #!/usr/bin/bash
      mkdir -p /home/dylan/repos
      cd /home/dylan/repos
      git clone https://github.com/dstathis/devconfig.git
      cd devconfig
      ./setup k --headless
  - path: /home/dylan/.ssh/id_rsa
    owner: 'dylan:dylan'
    permissions: '0700'
    defer: true
    content: |
      %private_key%
  - path: /home/dylan/.ssh/id_rsa.pub
    owner: 'dylan:dylan'
    permissions: '0700'
    defer: true
    content: |
      %public_key%
runcmd:
  - chown -R dylan:dylan /home/dylan
  - su dylan -c "/home/dylan/setup"
  - rm /home/dylan/setup
