#!/bin/bash

if [ -z ${1} ]; then
    read -p "Email for git: " gitemail
fi

. /etc/os-release

if [ ${ID_LIKE} == "debian" ]; then
    os=debian
elif [ ${ID} == "fedora" ]; then
    os=fedora
else
    echo "ERROR: Unknown OS" 1>&2
fi

pkgs=$(cat pkgs-common pkgs-${os} | sed '/#.*\|^$/d')

if [ ${os} == "fedora" ]; then
    rpm -q ${pkgs} > /dev/null
    if [ $? -ne 0 ]; then
            sudo dnf install -y ${pkgs}
    fi
fi

if [ ${os} == debian ]; then
    dpkg -V ${pkgs} 1>/dev/null 2>/dev/null
    if [ $? -ne 0 ]; then
        sudo apt install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew ${pkgs}
    fi
fi

mkdir -p ~/.config/i3 ~/bin
cp ./i3 ~/.config/i3/config
sudo cp i3status.conf /etc/i3status.conf
cp setvol ~/bin/

dconf load /com/gexperts/Tilix/ < tilix.dconf

cp aliases ~/.aliases

cp gitconfig ~/.gitconfig
if [ ! -z ${gitemail} ]; then
    sed -i "s/email = .*/email = ${gitemail}/g" ~/.gitconfig
fi

grep -q "\.aliases" ~/.bashrc
if [ $? -ne 0 ]; then
    echo '. ~/.aliases' >> ~/.bashrc
fi
grep -q 'ssh-add' ~/.bashrc
if [ $? -ne 0 ]; then
    echo "sshkeys=\$(\\ls ~/.ssh/id_* | grep -v '\\.pub')" >> ~/.bashrc
    echo 'ssh-add ${sshkeys} 2> /dev/null' >> ~/.bashrc
fi

# Setup vim
if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
mkdir -p ${HOME}/.vim/ftplugin
mkdir -p ${HOME}/.vim/indent
cp vimrc ${HOME}/.vimrc
mkdir -p ${HOME}/.vim/ftplugin
cp vimrc-python ${HOME}/.vim/ftplugin/python.vim
cp indent/* ${HOME}/.vim/indent/
mkdir -p ${HOME}/.vim/plugins
