#!/bin/bash

pkgs="i3 i3status dmenu i3lock xbacklight feh tilix pulseaudio-utils playerctl"

rpm -q ${pkgs}
if [ $? -ne 0 ]; then
	sudo dnf install ${pkgs}
fi

cp ./i3 ~/.config/i3/config
sudo cp i3status.conf /etc/i3status.conf
cp setvol ~/bin/

dconf load /com/gexperts/Tilix/ < tilix.dconf
