#!/bin/bash

if [ -z ${1} ]; then
	read -p "Email for git: " gitemail
fi

pkgs=$(cat pkgs | sed '/#.*\|^$/d')

rpm -q ${pkgs} > /dev/null
if [ $? -ne 0 ]; then
	sudo dnf install -y ${pkgs}
fi

mkdir -p ~/.config/i3 ~/bin
cp ./i3 ~/.config/i3/config
sudo cp i3status.conf /etc/i3status.conf
cp setvol ~/bin/

dconf load /com/gexperts/Tilix/ < tilix.dconf

cp aliases ~/.aliases

cp gitconfig ~/.gitconfig
if [ ! -z ${gitemail} ]; then
	sed -i "s/email = .*/email = ${gitemail}/g" ~/.gitconfig
fi

grep -q "\.aliases" ~/.bashrc
if [ $? -ne 0 ]; then
	echo '. ~/.aliases' >> ~/.bashrc
fi
grep -q 'ssh-add id_rsa\*\.pub' ~/.bashrc
if [ $? -ne 0 ]; then
	echo 'ssh-add id_rsa*.pub' >> ~/.bashrc
fi

# Setup vim
if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
mkdir -p ${HOME}/.vim/ftplugin
mkdir -p ${HOME}/.vim/indent
cp vimrc ${HOME}/.vimrc
cp indent/* ${HOME}/.vim/indent/
mkdir -p ${HOME}/.vim/plugins
